/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { getAsset, getAssetUrl } from '../utils/assetUtils'
import { MeshBasicMaterial, Texture } from 'three'

export function HallModel(props: any) {
  const { nodes, materials } = useGLTF(getAssetUrl('hall_model')) as any
  const texture = useTexture(getAssetUrl('lightmap_tex'), (tex) => {
    const hallLightmapTex = getAsset('lightmap_tex')
    const asset = tex as Texture
    asset.encoding = hallLightmapTex.options.encoding
    asset.flipY = hallLightmapTex.options.flipY
  })
  const foxtexture = useTexture(getAssetUrl('foxr_tex'), (tex) => {
    const texAsset = getAsset('foxr_tex')
    const asset = tex as Texture
    asset.encoding = texAsset.options.encoding
    asset.flipY = texAsset.options.flipY
  })
  const lightMapMaterial = useMemo(
    () =>
      new MeshBasicMaterial({
        map: texture
      }),
    []
  )
  const foxrMaterial = useMemo(
    () =>
      new MeshBasicMaterial({
        map: foxtexture
      }),
    []
  )

  return (
    <group {...props} dispose={null}>
      <group position={[8.14, 2.02, -1.85]}>
        <mesh
          geometry={nodes.bosch.geometry}
          material={materials.default}
          position={[0.14, -0.19, -0.32]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.degas.geometry}
          material={materials.default}
          position={[0.14, -0.91, 4.32]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.rembrandt.geometry}
          material={materials.default}
          position={[0.14, -0.42, 2.75]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.seurat.geometry}
          material={materials.default}
          position={[0.13, 0.01, 4.32]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.sorolla.geometry}
          material={materials.default}
          position={[0.14, -0.22, -3.79]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
      </group>
      <group position={[1.7, 0.9, -2.59]}>
        <mesh geometry={nodes.xnote000.geometry} material={materials.default} position={[0, 0.03, 0.48]} />
        <mesh geometry={nodes.xnote001.geometry} material={materials.default} position={[0, 0.03, 0.41]} />
        <mesh geometry={nodes.xnote002.geometry} material={materials.default} position={[0, 0.03, 0.35]} />
        <mesh geometry={nodes.xnote003.geometry} material={materials.default} position={[0, 0.03, 0.28]} />
        <mesh geometry={nodes.xnote004.geometry} material={materials.default} position={[0, 0.03, 0.21]} />
        <mesh geometry={nodes.xnote005.geometry} material={materials.default} position={[0, 0.03, 0.14]} />
        <mesh geometry={nodes.xnote006.geometry} material={materials.default} position={[0, 0.03, 0.07]} />
        <mesh geometry={nodes.xnote007.geometry} material={materials.default} position={[0, 0.02, 0]} />
        <mesh geometry={nodes.xnote008.geometry} material={materials.default} position={[0, 0.03, -0.07]} />
        <mesh geometry={nodes.xnote009.geometry} material={materials.default} position={[0, 0.03, -0.14]} />
        <mesh geometry={nodes.xnote010.geometry} material={materials.default} position={[0, 0.03, -0.21]} />
        <mesh geometry={nodes.xnote011.geometry} material={materials.default} position={[0, 0.03, -0.28]} />
        <mesh geometry={nodes.xnote012.geometry} material={materials.default} position={[0, 0.03, -0.35]} />
        <mesh
          geometry={nodes.xylobolts.geometry}
          material={materials.default}
          position={[0, 0.02, 0.49]}
          rotation={[0, Math.PI / 2, 0]}
        />
      </group>
      <mesh
        geometry={nodes.foxr.geometry}
        material={foxrMaterial}
        position={[4.04, 2.68, -7.21]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={2.65}
      />
      <mesh geometry={nodes.lightpanels.geometry} position={[-4.14, 3.96, 2.76]} rotation={[0, 0, -Math.PI]}>
        <meshBasicMaterial />
      </mesh>
      <mesh geometry={nodes.hall.geometry} material={lightMapMaterial} position={[-3.42, 0.49, 0.06]} />
      <mesh geometry={nodes.teleport.geometry} position={[-3.42, 0.49, 0.06]} scale={[0.1, 0.5, 0.1]} />
      <mesh geometry={nodes.sky.geometry} material={materials.default} scale={[1, 0.67, 1]} />
      <mesh geometry={nodes.clouds.geometry} rotation={[0.09, -0.68, 0.04]} scale={[0.75, 0.5, 0.75]} />
      <mesh
        geometry={nodes['xylostick-left'].geometry}
        material={lightMapMaterial}
        position={[1.7, 0.83, -2.03]}
        rotation={[1.64, -0.02, 0]}
      >
        <mesh geometry={nodes['xylostickball-left'].geometry} material={lightMapMaterial} position={[0, 0, -0.33]} />
      </mesh>
      <mesh
        geometry={nodes['xylostick-right'].geometry}
        material={lightMapMaterial}
        position={[1.7, 0.84, -3.01]}
        rotation={[1.54, 0.06, 0]}
      >
        <mesh geometry={nodes['xylostickball-right'].geometry} material={lightMapMaterial} position={[0, 0, -0.33]} />
      </mesh>
      <mesh geometry={nodes.screen.geometry} material={materials.default} position={[-3.42, 0.49, 0.06]} />
      <mesh
        geometry={nodes.graffiti.geometry}
        material={materials.default}
        position={[-3.42, 0.49, 0.05]}
        scale={[0.99, 1.02, 1]}
      />
      <mesh geometry={nodes.infopanel000.geometry} position={[-1.03, 0.67, -0.56]} />
      <mesh geometry={nodes.infopanel001.geometry} position={[1.3, 0.99, -3.53]} />
      <mesh geometry={nodes.infopanel002.geometry} position={[2.77, 0.67, 0.28]} />
      <mesh geometry={nodes.infopanel003.geometry} position={[-5.03, 0.67, 3.67]} />
      <mesh geometry={nodes.infopanel004.geometry} position={[-4.58, 0.67, -0.71]} />
      <mesh geometry={nodes.infopanel005.geometry} position={[-2.34, 0.67, -6.69]} />
      <mesh geometry={nodes.infopanel006.geometry} position={[2.86, 0.67, -6.28]} />
      <mesh geometry={nodes.infopanel007.geometry} position={[7.65, 0.45, -5.49]} />
      <mesh geometry={nodes.infopanel008.geometry} position={[7.76, 0.45, -2.12]} />
      <mesh geometry={nodes.infopanel009.geometry} position={[7.77, 0.65, 0.93]} />
      <mesh geometry={nodes.infopanel010.geometry} position={[7.59, 0.54, 3.31]} />
      <mesh geometry={nodes.infopanel012.geometry} position={[3.69, 0.67, 5.95]} />
      <mesh geometry={nodes.infopanel013.geometry} position={[-1.82, 0.67, 5.24]} />
      <mesh geometry={nodes.infopanel011.geometry} position={[7.59, 1.19, 3.31]} />
      <mesh geometry={nodes.infopanel014.geometry} position={[6.39, 0.77, -0.49]} />
      <mesh geometry={nodes.infopanel.geometry} position={[3.39, 1.47, 5.95]} />
      <mesh
        geometry={nodes.mozillamr.geometry}
        position={[2.03, 2.27, -7.2]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.18}
      />
      <mesh geometry={nodes.infopanel015.geometry} position={[0.75, 0.71, 2.19]} />
      <mesh geometry={nodes.doorC.geometry} position={[-1.72, 1.47, -7.24]} />
      <mesh geometry={nodes.doorA.geometry} position={[4.41, 1.45, 6.74]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.doorB.geometry} position={[-5.7, 1.41, 2.78]} rotation={[0, 1.57, 0]} />
    </group>
  )
}

useGLTF.preload(getAssetUrl('hall_model'))
